name: Run Webfetch Script

on:
  schedule:
    - cron: '*/10 7-21 * * *'  # Runs every 10 minutes between 7 AM and 9 PM
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to run in'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - testing
      dry-run:
        description: 'Run without making changes'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: |
          echo "Running in ${{ github.event.inputs.environment }} environment"
          if [ "${{ github.event.inputs.dry-run }}" == "true" ]; then
            echo "Dry run mode enabled - no changes will be made"
            python webfetch.py --dry-run
          else
            python webfetch.py
          fi

      - name: Configure Git
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: |
          git add ki_current_capacity_log.csv
          git diff-index --quiet HEAD || git commit -m "Update CSV with new capacity data [skip ci]"
          git push origin main
